# Generated by Django 4.1.4 on 2024-05-06 10:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productline_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('isactive', django.db.models.manager.Manager()),
            ],
        ),
    ]
