# Generated by Django 4.1.4 on 2024-05-07 14:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_managers_brand_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brand',
            managers=[
                ('objects_active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productline',
            managers=[
                ('objects_active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
