# Generated by Django 4.1.4 on 2024-05-07 15:24

from django.db import migrations
import drfecommerce.product.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_order_productline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='order',
            field=drfecommerce.product.fields.OrderField(blank=True),
        ),
    ]
