# Generated by Django 4.1.4 on 2024-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productline_order_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(blank=True, default='/test.jpg', null=True, upload_to=None),
        ),
    ]
