# Generated by Django 4.1.4 on 2024-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(blank=True, default='test.jpg', null=True, upload_to='product_image'),
        ),
    ]
